"""AgentCore Platform v1.0"""

# Step 7 — OutputValidate. S-3: belt-and-suspenders re-scan of the assembled
# report for subject-identifying content, independent of any upstream check
# (defense in depth — mirrors IMPLEMENTATION_LOG.md B5's
# SecurityGateOutputNode pattern). Reuses the same cue-word/digit-run/
# department/Japanese-script detectors as step 1 so there is exactly one
# PII-shape definition to maintain (see case_facts_ingest_service.py module
# docstring "Detection scope and honest limitation" for what this does and
# does not cover). Deliberately does NOT check for PLATFORM_MASK_TOKEN here —
# "[MASKED]" appearing in the assembled report is the safe, already-redacted
# state, not a leak.

from __future__ import annotations

from src.services.case_facts_ingest_service import (
    DEPARTMENT_CUE_RE,
    JAPANESE_SCRIPT_RE,
    NAME_CUE_RE,
    STUDENT_ID_RE,
)

MANDATORY_DISCLAIMER = (
    "> **AI DRAFT — NOT A FINAL DETERMINATION.** This report was generated by an AI "
    "assistant from anonymized case facts. It must be reviewed, verified, and finalized "
    "by an academic integrity officer and legal counsel before any official use.\n\n"
)


def find_subject_pii_violations(report_text: str) -> list[str]:
    violations: list[str] = []
    name_match = NAME_CUE_RE.search(report_text)
    if name_match:
        violations.append(f"possible subject name detected: '{name_match.group(0)}'")
    id_match = STUDENT_ID_RE.search(report_text)
    if id_match:
        violations.append(f"possible student ID detected: '{id_match.group(0)}'")
    dept_match = DEPARTMENT_CUE_RE.search(report_text)
    if dept_match:
        violations.append(f"possible department/affiliation detected: '{dept_match.group(0)}'")
    jp_match = JAPANESE_SCRIPT_RE.search(report_text)
    if jp_match:
        violations.append(f"possible Japanese-script identifier detected: '{jp_match.group(0)}'")
    return violations


def attach_disclaimer(report_text: str) -> str:
    return f"{MANDATORY_DISCLAIMER}{report_text}"
